/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#include "calibration.h"
#include "colors.h"
#include "widgetstyles.h"
#include "gui.h"

// GListeners
GListener gl;

// GHandles
GHandle ghContainerPageSplash;
GHandle ghlblFW;
GHandle ghLogo1;
GHandle ghLabel1;
GHandle ghProgbarLoad;
GHandle ghContainerPageGraph;
GHandle ghContainerLower;
GHandle ghlblW;
GHandle ghlblA;
GHandle ghlblV;
GHandle ghContainerUpper;
GHandle ghBtnTime;
GHandle ghBtnCh;
GHandle ghBtnSettings;
GHandle ghBtnScale;
GHandle ghImageUSB;
GHandle ghImageSDC;
GHandle ghlblElapsed;
GHandle ghContainerGraphC;
GHandle ghContainerGraphV;
GHandle ghContainerGraphW;
GHandle ghContainerGraphCV;
GHandle ghContainerGraphCV_1;
GHandle ghContainerGraphCV_2;
GHandle ghContainerRadio;
GHandle ghlblLine;
GHandle ghRadiobtnV;
GHandle ghRadiobtnW;
GHandle ghRadiobtnC;
GHandle ghRadiobtnCV;
GHandle ghListFreq;

// Fonts
font_t dejavu_sans_16;
font_t dejavu_sans_12_anti_aliased;
font_t dejavu_sans_16_anti_aliased;
font_t dejavu_sans_20_anti_aliased;

// Images
gdispImage DBlue_btn_g;
gdispImage DBlue_btn_c;
gdispImage menualt;
gdispImage DBlue_btn_s;

//static GDisplay* pixmap;

static void createPagePageSplash(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);


	// create container widget: ghContainerPageSplash
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 320;
	wi.g.height = 240;
	wi.g.parent = 0;
	wi.text = "Container";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerPageSplash = gwinContainerCreate(0, &wi, 0);

	// Create label widget: ghlblFW
	wi.g.show = TRUE;
	wi.g.x = 255;
	wi.g.y = 215;
	wi.g.width = 60;
	wi.g.height = 20;
	wi.g.parent = ghContainerPageSplash;
	wi.text = "FW: 0.02";
	wi.customDraw = gwinLabelDrawJustifiedCenter;
	wi.customParam = 0;
	wi.customStyle = &syfcgreen;
	ghlblFW = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghlblFW, FALSE);
	gwinSetFont(ghlblFW, dejavu_sans_12_anti_aliased);
	gwinRedraw(ghlblFW);

	// create button widget: ghLogo1
	wi.g.show = TRUE;
	wi.g.x = 65;
	wi.g.y = 80;
	wi.g.width = 200;
	wi.g.height = 25;
	wi.g.parent = ghContainerPageSplash;
	ghLogo1 = gwinImageCreate(0, &wi.g);
	gwinImageOpenFile(ghLogo1, "rsc/FCTextLogo.bmp");

	// Create label widget: ghLabel1
	wi.g.show = TRUE;
	wi.g.x = 105;
	wi.g.y = 120;
	wi.g.width = 120;
	wi.g.height = 20;
	wi.g.parent = ghContainerPageSplash;
	wi.text = "USB Tester 3.0";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = &syfcgreen;
	ghLabel1 = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghLabel1, FALSE);
	gwinSetFont(ghLabel1, dejavu_sans_16_anti_aliased);
	gwinRedraw(ghLabel1);

	// Create progressbar widget: ghProgbarLoad
	wi.g.show = TRUE;
	wi.g.x = 65;
	wi.g.y = 165;
	wi.g.width = 200;
	wi.g.height = 20;
	wi.g.parent = ghContainerPageSplash;
	wi.text = "Loading";
	wi.customDraw = gwinProgressbarDraw_Std;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghProgbarLoad = gwinProgressbarCreate(0, &wi);
	gwinProgressbarSetRange(ghProgbarLoad, 0, 100);
	gwinProgressbarSetPosition(ghProgbarLoad, 10);
}

static void createPagePageGraph(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);


	// create container widget: ghContainerPageGraph
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 320;
	wi.g.height = 240;
	wi.g.parent = 0;
	wi.text = "Container";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerPageGraph = gwinContainerCreate(0, &wi, 0);

	// create container widget: ghContainerGraphV
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 25;
	wi.g.width = 300;
	wi.g.height = 190;
	wi.g.parent = ghContainerPageGraph;
	wi.text = "";
	wi.customDraw = gwinContainerDraw_Std;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerGraphV = gwinContainerCreate(0, &wi, 0);

	// create container widget: ghContainerGraphCV
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 25;
	wi.g.width = 300;
	wi.g.height = 190;
	wi.g.parent = ghContainerPageGraph;
	wi.text = "";
	wi.customDraw = gwinContainerDraw_Std;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerGraphCV = gwinContainerCreate(0, &wi, 0);

	// create container widget: ghContainerUpper
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 326;
	wi.g.height = 25;
	wi.g.parent = ghContainerPageGraph;
	wi.text = "";
	wi.customDraw = gwinContainerDraw_Std;
	wi.customParam = 0;
	wi.customStyle = &sybar;
	ghContainerUpper = gwinContainerCreate(0, &wi, GWIN_CONTAINER_BORDER);

	// create container widget: ghContainerRadio
	wi.g.show = TRUE;
	wi.g.x = 300;
	wi.g.y = 24;
	wi.g.width = 20;
	wi.g.height = 195;
	wi.g.parent = ghContainerPageGraph;
	wi.text = "";
	wi.customDraw = gwinContainerDraw_Std;
	wi.customParam = 0;
	wi.customStyle = &sybar;
	ghContainerRadio = gwinContainerCreate(0, &wi, GWIN_CONTAINER_BORDER);

	// create container widget: ghContainerGraphW
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 25;
	wi.g.width = 300;
	wi.g.height = 190;
	wi.g.parent = ghContainerPageGraph;
	wi.text = "";
	wi.customDraw = gwinContainerDraw_Std;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerGraphW = gwinContainerCreate(0, &wi, 0);

	// create container widget: ghContainerGraphC
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 25;
	wi.g.width = 300;
	wi.g.height = 190;
	wi.g.parent = ghContainerPageGraph;
	wi.text = "";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerGraphC = gwinContainerCreate(0, &wi, 0);

	// create container widget: ghContainerLower
	wi.g.show = TRUE;
	wi.g.x = -6;
	wi.g.y = 215;
	wi.g.width = 326;
	wi.g.height = 25;
	wi.g.parent = ghContainerPageGraph;
	wi.text = "";
	wi.customDraw = gwinContainerDraw_Std;
	wi.customParam = 0;
	wi.customStyle = &sybar;
	ghContainerLower = gwinContainerCreate(0, &wi, GWIN_CONTAINER_BORDER);

	// create container widget: ghContainerGraphCV_2
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 95;
	wi.g.width = 300;
	wi.g.height = 95;
	wi.g.parent = ghContainerGraphCV;
	wi.text = "";
	wi.customDraw = gwinContainerDraw_Std;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerGraphCV_2 = gwinContainerCreate(0, &wi, 0);

	// create container widget: ghContainerGraphCV_1
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 300;
	wi.g.height = 95;
	wi.g.parent = ghContainerGraphCV;
	wi.text = "";
	wi.customDraw = gwinContainerDraw_Std;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerGraphCV_1 = gwinContainerCreate(0, &wi, 0);

	// Create label widget: ghlblW
	wi.g.show = TRUE;
	wi.g.x = 231;
	wi.g.y = 3;
	wi.g.width = 89;
	wi.g.height = 20;
	wi.g.parent = ghContainerLower;
	wi.text = "0.00W";
	wi.customDraw = gwinLabelDrawJustifiedRight;
	wi.customParam = 0;
	wi.customStyle = &sybar;
	ghlblW = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghlblW, FALSE);
	gwinSetFont(ghlblW, dejavu_sans_20_anti_aliased);
	gwinRedraw(ghlblW);

	// Create label widget: ghlblA
	wi.g.show = TRUE;
	wi.g.x = 95;
	wi.g.y = 3;
	wi.g.width = 135;
	wi.g.height = 20;
	wi.g.parent = ghContainerLower;
	wi.text = "0.00mA";
	wi.customDraw = gwinLabelDrawJustifiedRight;
	wi.customParam = 0;
	wi.customStyle = &sybar;
	ghlblA = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghlblA, FALSE);
	gwinSetFont(ghlblA, dejavu_sans_20_anti_aliased);
	gwinRedraw(ghlblA);

	// Create label widget: ghlblV
	wi.g.show = TRUE;
	wi.g.x = 6;
	wi.g.y = 3;
	wi.g.width = 90;
	wi.g.height = 20;
	wi.g.parent = ghContainerLower;
	wi.text = "0.00V";
	wi.customDraw = gwinLabelDrawJustifiedRight;
	wi.customParam = 0;
	wi.customStyle = &sybar;
	ghlblV = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghlblV, FALSE);
	gwinSetFont(ghlblV, dejavu_sans_20_anti_aliased);
	gwinRedraw(ghlblV);

	// create button widget: ghBtnTime
	wi.g.show = TRUE;
	wi.g.x = 119;
	wi.g.y = 0;
	wi.g.width = 60;
	wi.g.height = 25;
	wi.g.parent = ghContainerUpper;
	wi.text = "10Hz";
	wi.customDraw = gwinButtonDraw_Image;
	wi.customParam = &DBlue_btn_g;
	wi.customStyle = &sybtn;
	ghBtnTime = gwinButtonCreate(0, &wi);
	gwinSetFont(ghBtnTime, dejavu_sans_16_anti_aliased);
	gwinRedraw(ghBtnTime);

	// create button widget: ghBtnCh
	wi.g.show = TRUE;
	wi.g.x = 77;
	wi.g.y = 0;
	wi.g.width = 42;
	wi.g.height = 25;
	wi.g.parent = ghContainerUpper;
	wi.text = "CH1";
	wi.customDraw = gwinButtonDraw_Image;
	wi.customParam = &DBlue_btn_c;
	wi.customStyle = &sybtn;
	ghBtnCh = gwinButtonCreate(0, &wi);
	gwinSetFont(ghBtnCh, dejavu_sans_16_anti_aliased);
	gwinRedraw(ghBtnCh);

	// create button widget: ghBtnSettings
	wi.g.show = TRUE;
	wi.g.x = 299;
	wi.g.y = 2;
	wi.g.width = 20;
	wi.g.height = 20;
	wi.g.parent = ghContainerUpper;
	wi.text = "";
	wi.customDraw = gwinButtonDraw_Image;
	wi.customParam = &menualt;
	wi.customStyle = &white;
	ghBtnSettings = gwinButtonCreate(0, &wi);

	// create button widget: ghBtnScale
	wi.g.show = TRUE;
	wi.g.x = 179;
	wi.g.y = 0;
	wi.g.width = 70;
	wi.g.height = 25;
	wi.g.parent = ghContainerUpper;
	wi.text = "1000mA";
	wi.customDraw = gwinButtonDraw_Image;
	wi.customParam = &DBlue_btn_s;
	wi.customStyle = &white;
	ghBtnScale = gwinButtonCreate(0, &wi);
	gwinSetFont(ghBtnScale, dejavu_sans_16_anti_aliased);
	gwinRedraw(ghBtnScale);

	// create button widget: ghImageUSB
	wi.g.show = FALSE;
	wi.g.x = 252;
	wi.g.y = 1;
	wi.g.width = 24;
	wi.g.height = 24;
	wi.g.parent = ghContainerUpper;
	ghImageUSB = gwinImageCreate(0, &wi.g);
	gwinImageOpenFile(ghImageUSB, "rsc/USB blue.gif");

	// create button widget: ghImageSDC
	wi.g.show = FALSE;
	wi.g.x = 276;
	wi.g.y = 3;
	wi.g.width = 17;
	wi.g.height = 20;
	wi.g.parent = ghContainerUpper;
	ghImageSDC = gwinImageCreate(0, &wi.g);
	gwinImageOpenFile(ghImageSDC, "rsc/micro_sd.gif");

	// Create label widget: ghlblElapsed
	wi.g.show = TRUE;
	wi.g.x = 2;
	wi.g.y = 5;
	wi.g.width = 75;
	wi.g.height = 17;
	wi.g.parent = ghContainerUpper;
	wi.text = "00:00:00";
	wi.customDraw = gwinLabelDrawJustifiedRight;
	wi.customParam = 0;
	wi.customStyle = &sybar;
	ghlblElapsed = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghlblElapsed, FALSE);
	gwinSetFont(ghlblElapsed, dejavu_sans_16_anti_aliased);
	gwinRedraw(ghlblElapsed);

	// Create label widget: ghlblLine
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 63;
	wi.g.width = 20;
	wi.g.height = 27;
	wi.g.parent = ghContainerRadio;
	wi.text = "__";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = &sybar;
	ghlblLine = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghlblLine, FALSE);
	gwinSetFont(ghlblLine, dejavu_sans_20_anti_aliased);
	gwinRedraw(ghlblLine);

	// create radiobutton widget: ghRadiobtnV
	wi.g.show = TRUE;
	wi.g.x = 2;
	wi.g.y = 25;
	wi.g.width = 15;
	wi.g.height = 15;
	wi.g.parent = ghContainerRadio;
	wi.text = "1";
	wi.customDraw = gwinRadioDraw_Radio;
	wi.customParam = 0;
	wi.customStyle = &sybar;
	ghRadiobtnV = gwinRadioCreate(0, &wi, 0);
	gwinSetColor(ghRadiobtnV, white_studio);
	gwinSetBgColor(ghRadiobtnV, black_studio);

	// create radiobutton widget: ghRadiobtnW
	wi.g.show = TRUE;
	wi.g.x = 2;
	wi.g.y = 45;
	wi.g.width = 15;
	wi.g.height = 15;
	wi.g.parent = ghContainerRadio;
	wi.text = "2";
	wi.customDraw = gwinRadioDraw_Radio;
	wi.customParam = 0;
	wi.customStyle = &sybar;
	ghRadiobtnW = gwinRadioCreate(0, &wi, 0);
	gwinSetColor(ghRadiobtnW, white_studio);
	gwinSetBgColor(ghRadiobtnW, black_studio);

	// create radiobutton widget: ghRadiobtnC
	wi.g.show = TRUE;
	wi.g.x = 2;
	wi.g.y = 5;
	wi.g.width = 15;
	wi.g.height = 15;
	wi.g.parent = ghContainerRadio;
	wi.text = "0";
	wi.customDraw = gwinRadioDraw_Radio;
	wi.customParam = 0;
	wi.customStyle = &sybar;
	ghRadiobtnC = gwinRadioCreate(0, &wi, 0);
	gwinSetColor(ghRadiobtnC, white_studio);
	gwinSetBgColor(ghRadiobtnC, black_studio);
	gwinRadioPress(ghRadiobtnC);

	// create radiobutton widget: ghRadiobtnCV
	wi.g.show = TRUE;
	wi.g.x = 2;
	wi.g.y = 65;
	wi.g.width = 15;
	wi.g.height = 15;
	wi.g.parent = ghContainerRadio;
	wi.text = "3";
	wi.customDraw = gwinRadioDraw_Radio;
	wi.customParam = 0;
	wi.customStyle = &sybar;
	ghRadiobtnCV = gwinRadioCreate(0, &wi, 0);
	gwinSetColor(ghRadiobtnCV, white_studio);
	gwinSetBgColor(ghRadiobtnCV, black_studio);

	// Create list widget: ghListFreq
	wi.g.show = FALSE;
	wi.g.x = 118;
	wi.g.y = 25;
	wi.g.width = 61;
	wi.g.height = 120;
	wi.g.parent = ghContainerPageGraph;
	wi.text = "";
	wi.customDraw = gwinListDefaultDraw;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghListFreq = gwinListCreate(0, &wi, FALSE);
	gwinListSetScroll(ghListFreq, scrollSmooth);
	gwinSetFont(ghListFreq, dejavu_sans_16_anti_aliased);
	gwinRedraw(ghListFreq);
	gwinListAddItem(ghListFreq, "1Hz", FALSE);
	gwinListAddItem(ghListFreq, "2Hz", FALSE);
	gwinListAddItem(ghListFreq, "4Hz", FALSE);
	gwinListAddItem(ghListFreq, "8Hz", FALSE);
	gwinListAddItem(ghListFreq, "10Hz", FALSE);
	gwinListAddItem(ghListFreq, "20Hz", FALSE);
	gwinListSetSelected(ghListFreq, 0, FALSE);
	gwinListSetSelected(ghListFreq, 1, FALSE);
	gwinListSetSelected(ghListFreq, 2, FALSE);
	gwinListSetSelected(ghListFreq, 3, FALSE);
	gwinListSetSelected(ghListFreq, 4, TRUE);
	gwinListSetSelected(ghListFreq, 5, FALSE);
}

void guiShowPage(unsigned pageIndex)
{
	// Hide all pages
	gwinHide(ghContainerPageSplash);
	gwinHide(ghContainerPageGraph);

	// Show page selected page
	switch (pageIndex) {
	case 0:
		gwinShow(ghContainerPageSplash);
		break;

	case 1:
		gwinShow(ghContainerPageGraph);
		break;

	default:
		break;
	}
}

void guiCreate(void)
{
	GWidgetInit wi;

	// Prepare fonts
	dejavu_sans_16 = gdispOpenFont("DejaVuSans16");
	dejavu_sans_12_anti_aliased = gdispOpenFont("DejaVuSans12_aa");
	dejavu_sans_16_anti_aliased = gdispOpenFont("DejaVuSans16_aa");
	dejavu_sans_20_anti_aliased = gdispOpenFont("DejaVuSans20_aa");

	// Prepare images
	gdispImageOpenFile(&DBlue_btn_g, "rsc/DBlue_btn_g.bmp");
	gdispImageOpenFile(&DBlue_btn_c, "rsc/DBlue_btn_c.bmp");
	gdispImageOpenFile(&menualt, "rsc/menualt.gif");
	gdispImageOpenFile(&DBlue_btn_s, "rsc/DBlue_btn_s.bmp");

	// GWIN settings
	gwinWidgetClearInit(&wi);
	gwinSetDefaultFont(dejavu_sans_16);
	gwinSetDefaultStyle(&black, FALSE);
	gwinSetDefaultColor(black_studio);
	gwinSetDefaultBgColor(white_studio);

	// Create all the display pages
	createPagePageSplash();
	createPagePageGraph();

	// Select the default display page
	guiShowPage(0);

}

void guiEventLoop(void)
{
	GEvent* pe;

	while (1) {
		// Get an event
		pe = geventEventWait(&gl, 10);
		switch (pe->type) {
		}

	}
}

