/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#ifndef _GUI_H_
#define _GUI_H_

#include "gfx.h"

// Widget groups
#define GROUP_GRAPH 0
#define GROUP_DEFAULT 1

// GListeners
extern GListener gl;

// GHandles
extern GHandle ghContainerPageSplash;
extern GHandle ghlblFW;
extern GHandle ghLogo1;
extern GHandle ghLabel1;
extern GHandle ghProgbarLoad;
extern GHandle ghContainerPageGraph;
extern GHandle ghContainerLower;
extern GHandle ghlblW;
extern GHandle ghlblA;
extern GHandle ghlblV;
extern GHandle ghContainerUpper;
extern GHandle ghBtnTime;
extern GHandle ghBtnCh;
extern GHandle ghBtnSettings;
extern GHandle ghBtnScale;
extern GHandle ghImageUSB;
extern GHandle ghImageSDC;
extern GHandle ghlblElapsed;
extern GHandle ghContainerGraphC;
extern GHandle ghContainerGraphV;
extern GHandle ghContainerGraphW;
extern GHandle ghContainerGraphCV;
extern GHandle ghContainerGraphCV_1;
extern GHandle ghContainerGraphCV_2;
extern GHandle ghContainerRadio;
extern GHandle ghlblLine;
extern GHandle ghRadiobtnV;
extern GHandle ghRadiobtnW;
extern GHandle ghRadiobtnC;
extern GHandle ghRadiobtnCV;
extern GHandle ghListFreq;


// Function Prototypes
void guiCreate(void);
void guiShowPage(unsigned pageIndex);
void guiEventLoop(void);

#endif /* _GUI_H_ */

